### ISSUE TITLE
When you switch to "create project" in modal, advanced options disappear

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-catalog#491] opened 2017-10-11 18:25 UTC
When selecting a project I can choose "advanced options":
![screen shot 2017-10-11 at 2 23 49 pm](https://user-images.githubusercontent.com/280512/31459035-de8c3646-ae8f-11e7-93db-5e86b9569d93.png)

If I choose "create project" I no longer have advanced options:
![screen shot 2017-10-11 at 2 23 39 pm](https://user-images.githubusercontent.com/280512/31459042-e9f30a96-ae8f-11e7-8b24-f4aa9f02ad58.png)

Related to #477

**Comment by benjaminapetersen** [comment] 2017-10-11 18:29
This may be intentional as the "advanced options" page doesn't handle things related to projects (its a page within the context of a project), but it seems like we could support the flow.

**Comment by spadgett** [comment] 2017-10-17 19:32
Duplicate of

https://bugzilla.redhat.com/show_bug.cgi?id=1442978

and

https://github.com/openshift/origin-web-console/issues/1945

**Closed by spadgett** 2017-10-17 19:32 UTC
