### ISSUE TITLE
Same keyword can be set multiple times

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-catalog#617] opened 2018-01-10 15:22 UTC
Search for "ruby" from the search box in the nav.  Then filter by "ruby" using the filter by keyword input in the filter bar.  These are the same filter and should only show one badge.  Note clearing one of the badges clears both.

![screen shot 2018-01-10 at 10 19 22 am](https://user-images.githubusercontent.com/895728/34779984-d38eb924-f5ef-11e7-842e-f77045b265a0.PNG)

**Comment by dtaylor113** [comment] 2018-01-16 18:36
Hi, is there is still an issue here?

**Comment by rhamilto** [comment] 2018-01-16 18:44
> After discussion, this might actually be the desired behavior. Consensus is that it would be more confusing for the user to input a term and have nothing happen.

If that's the case, shouldn't the behavior be consistent regardless of which input your choose?  For example, if I input "ruby" in to the search box in the nav bar a second time, I only get one badge.  But I can get an unlimited number of "ruby" badges in the filter search input.

**Comment by rhamilto** [comment] 2018-01-16 18:45
LOTSA RUBY!

![screen shot 2018-01-16 at 1 44 50 pm](https://user-images.githubusercontent.com/895728/35006030-769db016-fac3-11e7-896d-5d44a80bff14.PNG)

**Comment by rhamilto** [comment] 2018-01-16 18:55
Ah!  I see what's going on.  The search input in the nav bar only allows a single keyword search regardless of the keyword; the filter search input allows n keyword searches.

**Comment by TheRealJon** [comment] 2018-01-24 19:09
@jwforres @spadgett @rhamilto Did we decide that this is not a bug?

**Comment by rhamilto** [comment] 2018-01-24 19:21
I think

> the filter search input allows n keyword searches.

is a bug, but it's an upstream bug in Angular-PatternFly, so we can probably close this issue and open one upstream if there is consensus it's a bug?  

Note:  data-toolbar-filter behaves the same way.
![screen shot 2018-01-24 at 2 19 42 pm](https://user-images.githubusercontent.com/895728/35352346-a88ef108-0111-11e8-8a87-8fdae3d07578.PNG)

**Comment by rhamilto** [comment] 2018-01-24 19:40
Interestingly, [pfFilterPanel](https://www.patternfly.org/angular-patternfly/#/api/patternfly.filters.component:pfFilterPanel) allows the same keyword multiple times.  [pfFilter](https://www.patternfly.org/angular-patternfly/#/api/patternfly.filters.component:pfFilter) and [pfToolbar](https://www.patternfly.org/angular-patternfly/#/api/patternfly.toolbars.component:pfToolbar) do not.    @jeff-phillips-18, @dtaylor113, @openshift/team-ux-review, any insight?

**Comment by dtaylor113** [comment] 2018-01-24 20:31
Looks like pfFilter does allow the same keyword twice, if cases are different.  Ie. "foo" and "Foo" are added.  I could see adding logic to pfFilterPanel to ignore a second keyword if case and text are the same.

**Comment by TheRealJon** [comment] 2018-01-24 21:47
Closing, see upstream issue: https://github.com/patternfly/angular-patternfly/issues/704

**Closed by TheRealJon** 2018-01-24 21:47 UTC
Labels: kind/bug, priority/P3
